name: RightClickFarming
version: @version@
main: me.daqem.rightclickfarming.RightClickFarming
api-version: 1.16
authors: [DAQEM]
description: Harverts crops and plant them back when you rightclick on them.
website: https://daqem.com
